// Code generated by go generate; DO NOT EDIT.
// To regenerate: go generate ./dbfixture/...

package dbfixture

import (
	"github.com/uptrace/uptrace/dbfixture/seedinput"
	"github.com/uptrace/uptrace/models"
)

// ---------------------------------------------------------------------------
// Loader name constants
// ---------------------------------------------------------------------------

const (
	ModelSlackNotifChannel      = "slack_notif_channel"
	ModelGoogleChatNotifChannel = "google_chat_notif_channel"
	ModelMattermostNotifChannel = "mattermost_notif_channel"
	ModelPagerdutyNotifChannel  = "pagerduty_notif_channel"
	ModelServicenowNotifChannel = "servicenow_notif_channel"
	ModelOpsgenieNotifChannel   = "opsgenie_notif_channel"
	ModelTelegramNotifChannel   = "telegram_notif_channel"
	ModelTeamsNotifChannel      = "teams_notif_channel"
	ModelWebhookNotifChannel    = "webhook_notif_channel"
)

// ---------------------------------------------------------------------------
// Constructor functions
// ---------------------------------------------------------------------------

// NewSlackNotifChannelLoader creates a loader for Slack notification channels.
func NewSlackNotifChannelLoader(f *Fixture, params LoaderParams) *notifChannelLoaderBase[seedinput.SlackNotifChannel, models.SlackNotifChannel] {
	return newNotifChannelLoader(f, params, ModelSlackNotifChannel, models.NotifChannelSlack,
		func(input *seedinput.SlackNotifChannel) *seedinput.BaseNotifChannel { return input.Base() },
		func(base *models.BaseNotifChannel) (*models.SlackNotifChannel, error) {
			ch := &models.SlackNotifChannel{BaseNotifChannel: base}
			if err := base.Params.Decode(&ch.Params); err != nil {
				return nil, err
			}
			return ch, nil
		},
		func() *models.SlackNotifChannel {
			return &models.SlackNotifChannel{BaseNotifChannel: new(models.BaseNotifChannel)}
		},
	)
}

// NewGoogleChatNotifChannelLoader creates a loader for GoogleChat notification channels.
func NewGoogleChatNotifChannelLoader(f *Fixture, params LoaderParams) *notifChannelLoaderBase[seedinput.GoogleChatNotifChannel, models.GoogleChatNotifChannel] {
	return newNotifChannelLoader(f, params, ModelGoogleChatNotifChannel, models.NotifChannelGoogleChat,
		func(input *seedinput.GoogleChatNotifChannel) *seedinput.BaseNotifChannel { return input.Base() },
		func(base *models.BaseNotifChannel) (*models.GoogleChatNotifChannel, error) {
			ch := &models.GoogleChatNotifChannel{BaseNotifChannel: base}
			if err := base.Params.Decode(&ch.Params); err != nil {
				return nil, err
			}
			return ch, nil
		},
		func() *models.GoogleChatNotifChannel {
			return &models.GoogleChatNotifChannel{BaseNotifChannel: new(models.BaseNotifChannel)}
		},
	)
}

// NewMattermostNotifChannelLoader creates a loader for Mattermost notification channels.
func NewMattermostNotifChannelLoader(f *Fixture, params LoaderParams) *notifChannelLoaderBase[seedinput.MattermostNotifChannel, models.MattermostNotifChannel] {
	return newNotifChannelLoader(f, params, ModelMattermostNotifChannel, models.NotifChannelMattermost,
		func(input *seedinput.MattermostNotifChannel) *seedinput.BaseNotifChannel { return input.Base() },
		func(base *models.BaseNotifChannel) (*models.MattermostNotifChannel, error) {
			ch := &models.MattermostNotifChannel{BaseNotifChannel: base}
			if err := base.Params.Decode(&ch.Params); err != nil {
				return nil, err
			}
			return ch, nil
		},
		func() *models.MattermostNotifChannel {
			return &models.MattermostNotifChannel{BaseNotifChannel: new(models.BaseNotifChannel)}
		},
	)
}

// NewPagerdutyNotifChannelLoader creates a loader for Pagerduty notification channels.
func NewPagerdutyNotifChannelLoader(f *Fixture, params LoaderParams) *notifChannelLoaderBase[seedinput.PagerdutyNotifChannel, models.PagerdutyNotifChannel] {
	return newNotifChannelLoader(f, params, ModelPagerdutyNotifChannel, models.NotifChannelPagerduty,
		func(input *seedinput.PagerdutyNotifChannel) *seedinput.BaseNotifChannel { return input.Base() },
		func(base *models.BaseNotifChannel) (*models.PagerdutyNotifChannel, error) {
			ch := &models.PagerdutyNotifChannel{BaseNotifChannel: base}
			if err := base.Params.Decode(&ch.Params); err != nil {
				return nil, err
			}
			return ch, nil
		},
		func() *models.PagerdutyNotifChannel {
			return &models.PagerdutyNotifChannel{BaseNotifChannel: new(models.BaseNotifChannel)}
		},
	)
}

// NewServicenowNotifChannelLoader creates a loader for Servicenow notification channels.
func NewServicenowNotifChannelLoader(f *Fixture, params LoaderParams) *notifChannelLoaderBase[seedinput.ServicenowNotifChannel, models.ServicenowNotifChannel] {
	return newNotifChannelLoader(f, params, ModelServicenowNotifChannel, models.NotifChannelServicenow,
		func(input *seedinput.ServicenowNotifChannel) *seedinput.BaseNotifChannel { return input.Base() },
		func(base *models.BaseNotifChannel) (*models.ServicenowNotifChannel, error) {
			ch := &models.ServicenowNotifChannel{BaseNotifChannel: base}
			if err := base.Params.Decode(&ch.Params); err != nil {
				return nil, err
			}
			return ch, nil
		},
		func() *models.ServicenowNotifChannel {
			return &models.ServicenowNotifChannel{BaseNotifChannel: new(models.BaseNotifChannel)}
		},
	)
}

// NewOpsgenieNotifChannelLoader creates a loader for Opsgenie notification channels.
func NewOpsgenieNotifChannelLoader(f *Fixture, params LoaderParams) *notifChannelLoaderBase[seedinput.OpsgenieNotifChannel, models.OpsgenieNotifChannel] {
	return newNotifChannelLoader(f, params, ModelOpsgenieNotifChannel, models.NotifChannelOpsgenie,
		func(input *seedinput.OpsgenieNotifChannel) *seedinput.BaseNotifChannel { return input.Base() },
		func(base *models.BaseNotifChannel) (*models.OpsgenieNotifChannel, error) {
			ch := &models.OpsgenieNotifChannel{BaseNotifChannel: base}
			if err := base.Params.Decode(&ch.Params); err != nil {
				return nil, err
			}
			return ch, nil
		},
		func() *models.OpsgenieNotifChannel {
			return &models.OpsgenieNotifChannel{BaseNotifChannel: new(models.BaseNotifChannel)}
		},
	)
}

// NewTelegramNotifChannelLoader creates a loader for Telegram notification channels.
func NewTelegramNotifChannelLoader(f *Fixture, params LoaderParams) *notifChannelLoaderBase[seedinput.TelegramNotifChannel, models.TelegramNotifChannel] {
	return newNotifChannelLoader(f, params, ModelTelegramNotifChannel, models.NotifChannelTelegram,
		func(input *seedinput.TelegramNotifChannel) *seedinput.BaseNotifChannel { return input.Base() },
		func(base *models.BaseNotifChannel) (*models.TelegramNotifChannel, error) {
			ch := &models.TelegramNotifChannel{BaseNotifChannel: base}
			if err := base.Params.Decode(&ch.Params); err != nil {
				return nil, err
			}
			return ch, nil
		},
		func() *models.TelegramNotifChannel {
			return &models.TelegramNotifChannel{BaseNotifChannel: new(models.BaseNotifChannel)}
		},
	)
}

// NewTeamsNotifChannelLoader creates a loader for Teams notification channels.
func NewTeamsNotifChannelLoader(f *Fixture, params LoaderParams) *notifChannelLoaderBase[seedinput.TeamsNotifChannel, models.TeamsNotifChannel] {
	return newNotifChannelLoader(f, params, ModelTeamsNotifChannel, models.NotifChannelTeams,
		func(input *seedinput.TeamsNotifChannel) *seedinput.BaseNotifChannel { return input.Base() },
		func(base *models.BaseNotifChannel) (*models.TeamsNotifChannel, error) {
			ch := &models.TeamsNotifChannel{BaseNotifChannel: base}
			if err := base.Params.Decode(&ch.Params); err != nil {
				return nil, err
			}
			return ch, nil
		},
		func() *models.TeamsNotifChannel {
			return &models.TeamsNotifChannel{BaseNotifChannel: new(models.BaseNotifChannel)}
		},
	)
}

// NewWebhookNotifChannelLoader creates a loader for Webhook notification channels.
func NewWebhookNotifChannelLoader(f *Fixture, params LoaderParams) *notifChannelLoaderBase[seedinput.WebhookNotifChannel, models.WebhookNotifChannel] {
	return newNotifChannelLoader(f, params, ModelWebhookNotifChannel, models.NotifChannelWebhook,
		func(input *seedinput.WebhookNotifChannel) *seedinput.BaseNotifChannel { return input.Base() },
		func(base *models.BaseNotifChannel) (*models.WebhookNotifChannel, error) {
			ch := &models.WebhookNotifChannel{BaseNotifChannel: base}
			if err := base.Params.Decode(&ch.Params); err != nil {
				return nil, err
			}
			return ch, nil
		},
		func() *models.WebhookNotifChannel {
			return &models.WebhookNotifChannel{BaseNotifChannel: new(models.BaseNotifChannel)}
		},
	)
}

// ---------------------------------------------------------------------------
// Registration and seeding helpers
// ---------------------------------------------------------------------------

// registerNotifChannelLoaders registers all notification channel loaders
// in the fixture registry.
func registerNotifChannelLoaders(f *Fixture, p LoaderParams) {
	f.Register(ModelSlackNotifChannel, Wrap(NewSlackNotifChannelLoader(f, p)))
	f.Register(ModelGoogleChatNotifChannel, Wrap(NewGoogleChatNotifChannelLoader(f, p)))
	f.Register(ModelMattermostNotifChannel, Wrap(NewMattermostNotifChannelLoader(f, p)))
	f.Register(ModelPagerdutyNotifChannel, Wrap(NewPagerdutyNotifChannelLoader(f, p)))
	f.Register(ModelServicenowNotifChannel, Wrap(NewServicenowNotifChannelLoader(f, p)))
	f.Register(ModelOpsgenieNotifChannel, Wrap(NewOpsgenieNotifChannelLoader(f, p)))
	f.Register(ModelTelegramNotifChannel, Wrap(NewTelegramNotifChannelLoader(f, p)))
	f.Register(ModelTeamsNotifChannel, Wrap(NewTeamsNotifChannelLoader(f, p)))
	f.Register(ModelWebhookNotifChannel, Wrap(NewWebhookNotifChannelLoader(f, p)))
}

// seedNotifChannels seeds all notification channel types from SeedData.
func seedNotifChannels(seed *seedinput.SeedData, seedOne func(string, any) error) error {
	nc := &seed.NotifChannels
	for _, ch := range nc.Slack {
		if err := seedOne(ModelSlackNotifChannel, ch); err != nil {
			return err
		}
	}
	for _, ch := range nc.GoogleChat {
		if err := seedOne(ModelGoogleChatNotifChannel, ch); err != nil {
			return err
		}
	}
	for _, ch := range nc.Mattermost {
		if err := seedOne(ModelMattermostNotifChannel, ch); err != nil {
			return err
		}
	}
	for _, ch := range nc.Pagerduty {
		if err := seedOne(ModelPagerdutyNotifChannel, ch); err != nil {
			return err
		}
	}
	for _, ch := range nc.Servicenow {
		if err := seedOne(ModelServicenowNotifChannel, ch); err != nil {
			return err
		}
	}
	for _, ch := range nc.Opsgenie {
		if err := seedOne(ModelOpsgenieNotifChannel, ch); err != nil {
			return err
		}
	}
	for _, ch := range nc.Telegram {
		if err := seedOne(ModelTelegramNotifChannel, ch); err != nil {
			return err
		}
	}
	for _, ch := range nc.Teams {
		if err := seedOne(ModelTeamsNotifChannel, ch); err != nil {
			return err
		}
	}
	for _, ch := range nc.Webhook {
		if err := seedOne(ModelWebhookNotifChannel, ch); err != nil {
			return err
		}
	}
	return nil
}
